namespace: zer0glitch
name: collector
version: 0.0.19
readme: README.md
authors:
- Kat Morgan <usrbinkat@codectl.io>
description: 'CodeSparta Koffer Artifact Collector Automation'
tags:
  - iac
  - upi
  - openshift
  - disconnected
  - airgap
  - ocp
dependencies:
        #"containers.podman": ">=1.4.3"
  "containers.podman": ">=1.4.3"
license:
- GPL-3.0-only
repository: http://github.com/zer0glitch/collector
issues: https://github.com/zer0glitch/collector/issues
documentation: http://codectl.io
homepage: http://codectl.io
build_ignore:
  - ci
  - tests/output
  - build_artifact
  - "*.tar.gz"
  - ".gitignore"
  - ".history"
  - ".vscode"
  - ".idea"
  - ".github"
  - contrib
  - importer_result.json
